---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - svc.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: sabnzbd
configMapGenerator:
  - name: scripts
    files:
      - "scripts/clean.py"
      - "scripts/replace_for.py"
